filter:
    excluded_paths:
        - 'vendor/*'
before_commands:
    - 'composer install'
tools:
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR2
    sensiolabs_security_checker: true
    php_loc:
        excluded_dirs:
            - vendor
    php_pdepend: true
    php_sim: true
build_failure_conditions:
  - 'issues.label("coding-style").new.exists'
  - 'elements.rating(< B).new.exists'
  - 'project.metric("scrutinizer.quality", < 9)'
  - 'issues.severity(>= MAJOR).new.exists'
